sudo: required
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - python3 -m pip install --upgrade pip setuptools wheel
install:
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install -n base -c conda-forge mamba --yes
  - conda activate base
#  - pip3 install git+https://github.com/nextstrain/cli
#  - nextstrain version
#  - nextstrain check-setup
#  - nextstrain update
script:
  - mkdir -p data/

